import { useEffect, useState } from "react";
import { ArrowRight } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { getOpportunities } from "../../../api/opportunityApi";
import { getPendingPreSalesAssignments } from "../../../api/preSalesAssignmentApi";
import { getPocsByOpportunity } from "../../../api/pocApi";
import { ROLES } from "../../../auth/roles";
import { useAuth } from "../../../context/AuthContext";

export default function Phase5RolePanel(){
 const {activeRole}=useAuth();const navigate=useNavigate();const[items,setItems]=useState([]);const[pocItems,setPocItems]=useState([]);const[error,setError]=useState("");
 useEffect(()=>{let mounted=true;const load=async()=>{try{if(activeRole===ROLES.PRE_SALES_MANAGER){setItems(await getPendingPreSalesAssignments()||[]);setPocItems([]);}else if(activeRole===ROLES.SOLUTION_ENGINEER){const opportunities=await getOpportunities();const pairs=await Promise.all((opportunities||[]).slice(0,20).map(async o=>({o,pocs:await getPocsByOpportunity(o.opportunity_id).catch(()=>[])})));setItems(opportunities||[]);setPocItems(pairs.flatMap(({o,pocs})=>pocs.filter(p=>["Approved","In Progress","Submitted"].includes(p.status)).map(p=>({...p,opportunity_name:o.opportunity_name}))));}setError("");}catch(e){if(mounted)setError(e?.response?.data?.message||"Unable to load technical workflow.");}};if([ROLES.PRE_SALES_MANAGER,ROLES.SOLUTION_ENGINEER].includes(activeRole))load();return()=>{mounted=false;};},[activeRole]);
 if(activeRole===ROLES.PRE_SALES_MANAGER)return <div className="dashboard-pending-grid"><button type="button" className="dashboard-pending-card" onClick={()=>navigate("/pre-sales/assignments")}><span className="dashboard-pending-icon">◌</span><span className="dashboard-pending-copy"><strong>Pending Technical Assignments</strong><b>{items.length}</b><small>Awaiting Solution Engineer allocation</small></span><span className="dashboard-pending-link">View queue <ArrowRight size={13}/></span></button></div>;
 return <section className="figma-card dashboard-role-workflow-panel"><div className="figma-card-header"><div><h3>Technical Workspace</h3><p>Opportunities and POCs assigned to you as a Solution Engineer.</p></div></div>{error?<p className="standard-error">{error}</p>:<><div className="dashboard-list">{items.slice(0,5).map(item=><button key={item.opportunity_id} className="dashboard-workflow-item" onClick={()=>navigate(`/opportunity/${item.opportunity_id}`)}><strong>{item.opportunity_name}</strong><span>{item.account_name||`Opportunity #${item.opportunity_id}`} · {item.current_stage?.stage_name||item.status}</span></button>)}{!items.length&&<div className="figma-dashboard-empty"><strong>No assigned opportunities</strong></div>}</div><div className="dashboard-workflow-pocs"><h3>POCs In Progress</h3>{pocItems.slice(0,5).map(p=><button key={p.poc_id} className="dashboard-workflow-item" onClick={()=>navigate(`/opportunity/${p.opportunity_id}`)}><strong>{p.poc_name}</strong><span>{p.opportunity_name} · {p.status}</span></button>)}{!pocItems.length&&<p>No active POCs require attention.</p>}</div></>}</section>;
}