import { useEffect, useState } from "react";
import { ArrowRight, Building2, MapPin, RefreshCw, Search, Users } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { getAccounts } from "../api/accountApi";
import { useAuth } from "../context/AuthContext";
import { ROLES } from "../auth/roles";
import PageHeader from "../components/ui/PageHeader";
import Card from "../components/ui/Card";
import Button from "../components/ui/Button";
import SearchInput from "../components/ui/SearchInput";
import EmptyState from "../components/ui/EmptyState";
import KpiCard from "../components/ui/KpiCard";

export default function Accounts(){ const {activeRole}=useAuth(); const navigate=useNavigate(); const [accounts,setAccounts]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [search,setSearch]=useState(""); const load=async()=>{try{setLoading(true);setError("");setAccounts(await getAccounts());}catch(err){setError(err?.response?.data?.message||"Unable to load accounts.");}finally{setLoading(false);}}; useEffect(()=>{load();},[activeRole]); if(![ROLES.SALES_EXECUTIVE,ROLES.SALES_MANAGER].includes(activeRole))return <div className="standard-page"><PageHeader title="Accounts" description="You do not have access to this page."/></div>; const q=search.trim().toLowerCase(); const visible=accounts.filter(a=>!q||[a.account_name,a.industry,a.city,a.state,a.country,a.website].filter(Boolean).some(v=>String(v).toLowerCase().includes(q))); return <div className="standard-page exec-record-page"><PageHeader title="My Accounts" description="Customer accounts available within your sales scope." actions={<Button variant="secondary" onClick={load}><RefreshCw size={14}/> Refresh</Button>}/>{error&&<div className="standard-error">{error}</div>}<div className="ui-kpi-grid"><KpiCard icon={Building2} label="Total accounts" value={accounts.length} description="Accounts in sales scope" /><KpiCard icon={Search} label="Showing" value={visible.length} description="Current result set" /><KpiCard icon={Users} label="Customer coverage" value={visible.length} description="Visible accounts" /><KpiCard icon={MapPin} label="Locations" value={new Set(visible.map(a=>[a.city,a.state,a.country].filter(Boolean).join(", ")).filter(Boolean)).size} description="Distinct locations" /></div><Card padding={false}><div className="exec-record-toolbar"><SearchInput value={search} onChange={setSearch} placeholder="Search accounts, industry, location..."/></div>{loading?<div className="table-loading">Loading accounts…</div>:<div className="exec-account-grid">{visible.map(a=><button key={a.account_id} onClick={()=>navigate(`/opportunities?account=${a.account_id}`)}><span className="exec-account-avatar"><Building2 size={18}/></span><div><strong>{a.account_name}</strong><span>{a.industry||"Industry not specified"}</span><small>{[a.city,a.state,a.country].filter(Boolean).join(", ")||"Location not specified"}</small></div><ArrowRight size={16}/></button>)}{!visible.length&&<EmptyState message={q?"No matching accounts":"No authorized accounts"}/>}</div>}</Card></div>; }
