import {useEffect,useState} from "react";
import {Building2,RefreshCw,Plus} from "lucide-react";
import api from "../api/axiosClient";
import {ROLES} from "../auth/roles"; import {useAuth} from "../context/AuthContext";
import PageHeader from "../components/ui/PageHeader"; import Card from "../components/ui/Card"; import Button from "../components/ui/Button"; import EmptyState from "../components/ui/EmptyState"; import StatusBadge from "../components/ui/StatusBadge";
export default function OemRegistry(){const {activeRole}=useAuth();const [rows,setRows]=useState([]),[error,setError]=useState(""),[showCreate,setShowCreate]=useState(false),[form,setForm]=useState({partner_name:"",product_name:"",account_id:""});const leadership=activeRole===ROLES.LEADERSHIP;const load=async()=>{try{setRows((await api.get("/oem/")).data);setError("")}catch(e){setError(e?.response?.data?.message||"Unable to load OEMs.")}};useEffect(()=>{load()},[activeRole]);const create=async e=>{e.preventDefault();try{await api.post("/oem/",form);setForm({partner_name:"",product_name:"",account_id:""});load()}catch(x){setError(x?.response?.data?.message||"Unable to create OEM.")}};return <div className="standard-page"><PageHeader title="OEM Registry" description={leadership?"Full OEM master governance.":"OEM names and products are visible; contact details are redacted for employees."} actions={<><Button variant="secondary" onClick={load}><RefreshCw size={14}/>Refresh</Button>{leadership&&<Button onClick={()=>setShowCreate(v=>!v)}><Plus size={14}/>{showCreate?"Close":"Add OEM"}</Button>}</>}/>{error&&<div className="standard-error">{error}</div>}{leadership&&showCreate&&<Card><form id="oem-create" onSubmit={create} style={{display:"grid",gap:10}}><input required placeholder="OEM name" value={form.partner_name} onChange={e=>setForm({...form,partner_name:e.target.value})}/><input required placeholder="Product" value={form.product_name} onChange={e=>setForm({...form,product_name:e.target.value})}/><input required placeholder="Contact Person Name" value={form.contact_person||""} onChange={e=>setForm({...form,contact_person:e.target.value.replace(/[^A-Za-z .'-]/g,"")})}/><input type="email" placeholder="Email" value={form.email||""} onChange={e=>setForm({...form,email:e.target.value})}/><input
required
type="tel"
placeholder="10-digit phone number"
inputMode="numeric"
maxLength={10}
pattern="[0-9]{10}"
value={form.phone||""}
onChange={e=>setForm({...form,phone:e.target.value.replace(/\D/g,"").slice(0,10)})}
/><Button type="submit">Create OEM</Button></form></Card>}<Card padding={false}>{rows.length?rows.map(o=><div key={o.oem_partner_id} style={{padding:16,borderBottom:"1px solid var(--border)",display:"flex",gap:12,alignItems:"center"}}><Building2 size={18}/><div style={{flex:1}}><strong>{o.partner_name}</strong><small>{o.product_name} · Account #{o.account_id}</small></div><StatusBadge status={o.status}/>{leadership&&<small>{o.contact_person||"No contact"} {o.email||""}</small>}</div>):<EmptyState message="No OEM partners found."/>}</Card></div>}
