ACCESS_TOKEN_EXPIRES_MINUTES = 20

REFRESH_TOKEN_EXPIRES_DAYS = 7

SESSION_WARNING_MINUTES = 5

STATUS_PENDING = "PENDING"

STATUS_APPROVED = "APPROVED"

STATUS_REVOKED = "REVOKED"

ROLE_ADMIN = "Admin"