POC_OUTCOME_SUCCESS = "Success"
POC_OUTCOME_FAILURE = "Failure"
POC_OUTCOME_ONGOING = "Ongoing"
POC_OUTCOME_ABANDONED = "Abandoned"

POC_OUTCOMES = [
    POC_OUTCOME_SUCCESS,
    POC_OUTCOME_FAILURE,
    POC_OUTCOME_ONGOING,
    POC_OUTCOME_ABANDONED,
]

POC_STATUS_DRAFT = "Draft"
POC_STATUS_IN_PROGRESS = "In Progress"
POC_STATUS_SUBMITTED = "Submitted"
POC_STATUS_COMPLETED = "Completed"

POC_STATUSES = [
    POC_STATUS_DRAFT,
    POC_STATUS_IN_PROGRESS,
    POC_STATUS_SUBMITTED,
    POC_STATUS_COMPLETED,
]
