SALES_EXECUTIVE = "Sales Executive"
PRE_SALES_CONSULTANT = "Pre-Sales Consultant"
SALES_MANAGER = "Sales Manager"
PRE_SALES_MANAGER = "Pre-Sales Manager"
ADMIN = "Admin"

DEFAULT_ROLE = SALES_EXECUTIVE

AVAILABLE_ROLES = [
    SALES_EXECUTIVE,
    PRE_SALES_CONSULTANT,
    SALES_MANAGER,
    PRE_SALES_MANAGER,
    ADMIN,
]