"""add POC assignments

Revision ID: 1ec640fce501
Revises: 35a1d78f5b1d
Create Date: 2026-09-09 10:55:28.923476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ec640fce501'
down_revision: Union[str, Sequence[str], None] = '35a1d78f5b1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poc_assignments',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('poc_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['poc_id'], ['poc_tracker.poc_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('assignment_id'),
    sa.UniqueConstraint('poc_id', 'user_id', name='uq_poc_assignment_user')
    )
    op.create_index(op.f('ix_poc_assignments_assigned_by'), 'poc_assignments', ['assigned_by'], unique=False)
    op.create_index(op.f('ix_poc_assignments_is_active'), 'poc_assignments', ['is_active'], unique=False)
    op.create_index(op.f('ix_poc_assignments_poc_id'), 'poc_assignments', ['poc_id'], unique=False)
    op.create_index(op.f('ix_poc_assignments_user_id'), 'poc_assignments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_poc_assignments_user_id'), table_name='poc_assignments')
    op.drop_index(op.f('ix_poc_assignments_poc_id'), table_name='poc_assignments')
    op.drop_index(op.f('ix_poc_assignments_is_active'), table_name='poc_assignments')
    op.drop_index(op.f('ix_poc_assignments_assigned_by'), table_name='poc_assignments')
    op.drop_table('poc_assignments')
    # ### end Alembic commands ###
