"""add opportunity OEM associations

Revision ID: 35a1d78f5b1d
Revises: h9i0j1k2l3m4
Create Date: 2026-09-09 07:28:53.134734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35a1d78f5b1d'
down_revision: Union[str, Sequence[str], None] = 'h9i0j1k2l3m4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity_oems',
    sa.Column('opportunity_oem_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('oem_partner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['oem_partner_id'], ['oem_partners.oem_partner_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.opportunity_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('opportunity_oem_id'),
    sa.UniqueConstraint('opportunity_id', 'oem_partner_id', name='uq_opportunity_oem')
    )
    op.create_index(op.f('ix_opportunity_oems_oem_partner_id'), 'opportunity_oems', ['oem_partner_id'], unique=False)
    op.create_index(op.f('ix_opportunity_oems_opportunity_id'), 'opportunity_oems', ['opportunity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunity_oems_opportunity_id'), table_name='opportunity_oems')
    op.drop_index(op.f('ix_opportunity_oems_oem_partner_id'), table_name='opportunity_oems')
    op.drop_table('opportunity_oems')
    # ### end Alembic commands ###
