"""Deal Room V2 baseline

Revision ID: 60ba9620bb40
Revises: 
Create Date: 2026-09-23 22:50:48.304309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60ba9620bb40'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=200), nullable=False),
    sa.Column('canonical_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_index(op.f('ix_accounts_account_name'), 'accounts', ['account_name'], unique=False)
    op.create_index(op.f('ix_accounts_canonical_name'), 'accounts', ['canonical_name'], unique=True)
    op.create_index(op.f('ix_accounts_status'), 'accounts', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('audit_log_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('actor_active_role', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('audit_log_id')
    )
    op.create_table('stage_master',
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=100), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('requires_poc', sa.Boolean(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('is_won', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('stage_id')
    )
    op.create_index(op.f('ix_stage_master_stage_name'), 'stage_master', ['stage_name'], unique=True)
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('auth_version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_manager_id'), 'users', ['manager_id'], unique=False)
    op.create_table('contacts',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notifications_entity_id'), 'notifications', ['entity_id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_user_id'), 'notifications', ['recipient_user_id'], unique=False)
    op.create_table('oem_partners',
    sa.Column('oem_partner_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('partner_name', sa.String(length=150), nullable=False),
    sa.Column('product_name', sa.String(length=150), nullable=False),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('oem_partner_id')
    )
    op.create_index(op.f('ix_oem_partners_account_id'), 'oem_partners', ['account_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('sales_owner_id', sa.Integer(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pain_points', sa.Text(), nullable=True),
    sa.Column('estimated_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('final_revenue', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('lifecycle_stage', sa.String(length=30), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('operational_status', sa.String(length=20), nullable=False),
    sa.Column('review_status', sa.String(length=40), nullable=False),
    sa.Column('lost_reason', sa.String(length=100), nullable=True),
    sa.Column('lost_explanation', sa.Text(), nullable=True),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(outcome = 'Open' AND operational_status IN ('Active','Stalled')) OR (outcome IN ('Closed Won','Closed Lost') AND operational_status = 'Closed')", name='ck_opportunities_v2_closed_consistency'),
    sa.CheckConstraint("lifecycle_stage IS NULL OR lifecycle_stage IN ('Lead','Qualified','RFX','POC','Negotiations','Delivery')", name='ck_opportunities_v2_lifecycle_stage'),
    sa.CheckConstraint("operational_status IN ('Active','Stalled','Closed')", name='ck_opportunities_v2_operational_status'),
    sa.CheckConstraint("review_status IN ('Draft','Pending Sales Manager Review','Approved')", name='ck_opportunities_v2_review_status'),
    sa.CheckConstraint('final_revenue IS NULL OR final_revenue >= 0', name='ck_opportunities_final_revenue_non_negative'),
    sa.CheckConstraint('row_version >= 1', name='ck_opportunities_v2_row_version_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['sales_owner_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stage_master.stage_id'], ),
    sa.PrimaryKeyConstraint('opportunity_id')
    )
    op.create_index(op.f('ix_opportunities_account_id'), 'opportunities', ['account_id'], unique=False)
    op.create_index(op.f('ix_opportunities_created_by'), 'opportunities', ['created_by'], unique=False)
    op.create_index(op.f('ix_opportunities_lifecycle_stage'), 'opportunities', ['lifecycle_stage'], unique=False)
    op.create_index(op.f('ix_opportunities_operational_status'), 'opportunities', ['operational_status'], unique=False)
    op.create_index(op.f('ix_opportunities_outcome'), 'opportunities', ['outcome'], unique=False)
    op.create_index(op.f('ix_opportunities_review_status'), 'opportunities', ['review_status'], unique=False)
    op.create_index(op.f('ix_opportunities_row_version'), 'opportunities', ['row_version'], unique=False)
    op.create_index(op.f('ix_opportunities_sales_owner_id'), 'opportunities', ['sales_owner_id'], unique=False)
    op.create_index(op.f('ix_opportunities_stage_id'), 'opportunities', ['stage_id'], unique=False)
    op.create_index(op.f('ix_opportunities_status'), 'opportunities', ['status'], unique=False)
    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_blocklist_jti'), 'token_blocklist', ['jti'], unique=True)
    op.create_index(op.f('ix_token_blocklist_user_id'), 'token_blocklist', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role', name='uq_user_role')
    )
    op.create_index(op.f('ix_user_roles_role'), 'user_roles', ['role'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('user_system_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'permission', name='uq_user_system_permission')
    )
    op.create_index(op.f('ix_user_system_permissions_permission'), 'user_system_permissions', ['permission'], unique=False)
    op.create_index(op.f('ix_user_system_permissions_user_id'), 'user_system_permissions', ['user_id'], unique=False)
    op.create_table('closed_won_requests',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('requested_active_role', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_active_role', sa.String(length=100), nullable=True),
    sa.Column('resolution_reason', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('Pending', 'Approved', 'Rejected')", name='ck_closed_won_requests_status'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.opportunity_id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('request_id'),
    sa.UniqueConstraint('opportunity_id', name='uq_closed_won_requests_opportunity')
    )
    op.create_index(op.f('ix_closed_won_requests_opportunity_id'), 'closed_won_requests', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_closed_won_requests_status'), 'closed_won_requests', ['status'], unique=False)
    op.create_table('delivery_projects',
    sa.Column('delivery_project_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['manager_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.opportunity_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('delivery_project_id')
    )
    op.create_index(op.f('ix_delivery_projects_account_id'), 'delivery_projects', ['account_id'], unique=False)
    op.create_index(op.f('ix_delivery_projects_manager_id'), 'delivery_projects', ['manager_id'], unique=False)
    op.create_index(op.f('ix_delivery_projects_opportunity_id'), 'delivery_projects', ['opportunity_id'], unique=True)
    op.create_table('follow_ups',
    sa.Column('follow_up_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.opportunity_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('follow_up_id')
    )
    op.create_index(op.f('ix_follow_ups_due_date'), 'follow_ups', ['due_date'], unique=False)
    op.create_index(op.f('ix_follow_ups_opportunity_id'), 'follow_ups', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_follow_ups_owner_id'), 'follow_ups', ['owner_id'], unique=False)
    op.create_table('negotiation_contexts',
    sa.Column('negotiation_context_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('nda_suggested', sa.Boolean(), nullable=False),
    sa.Column('nda_link', sa.Text(), nullable=True),
    sa.Column('msa_link', sa.Text(), nullable=True),
    sa.Column('sow_link', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.opportunity_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('negotiation_context_id'),
    sa.UniqueConstraint('opportunity_id')
    )
    op.create_table('opportunity_oems',
    sa.Column('opportunity_oem_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('oem_partner_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['oem_partner_id'], ['oem_partners.oem_partner_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.opportunity_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('opportunity_oem_id')
    )
    op.create_index(op.f('ix_opportunity_oems_oem_partner_id'), 'opportunity_oems', ['oem_partner_id'], unique=False)
    op.create_index(op.f('ix_opportunity_oems_opportunity_id'), 'opportunity_oems', ['opportunity_id'], unique=False)
    op.create_table('opportunity_team',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.opportunity_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('team_id'),
    sa.UniqueConstraint('opportunity_id', 'user_id', 'role', name='uq_opportunity_team_member_role')
    )
    op.create_index(op.f('ix_opportunity_team_opportunity_id'), 'opportunity_team', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_opportunity_team_user_id'), 'opportunity_team', ['user_id'], unique=False)
    op.create_table('opportunity_value_history',
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('old_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('new_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=2000), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('actor_active_role', sa.String(length=100), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('opportunity_row_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('new_value >= 0', name='ck_opportunity_value_history_new_non_negative'),
    sa.CheckConstraint('old_value IS NULL OR old_value >= 0', name='ck_opportunity_value_history_old_non_negative'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.opportunity_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_opportunity_value_history_actor_active_role'), 'opportunity_value_history', ['actor_active_role'], unique=False)
    op.create_index(op.f('ix_opportunity_value_history_actor_id'), 'opportunity_value_history', ['actor_id'], unique=False)
    op.create_index(op.f('ix_opportunity_value_history_changed_at'), 'opportunity_value_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_opportunity_value_history_opportunity_id'), 'opportunity_value_history', ['opportunity_id'], unique=False)
    op.create_table('poc_tracker',
    sa.Column('poc_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('poc_name', sa.String(length=150), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('success_metric', sa.Text(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('failure_condition', sa.Text(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=True),
    sa.Column('input_drive_link', sa.Text(), nullable=True),
    sa.Column('result_view_link', sa.Text(), nullable=True),
    sa.Column('submission_metadata', sa.JSON(), nullable=True),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('exit_criteria', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('Draft','In Progress','Submitted','Completed')", name='ck_poc_tracker_status'),
    sa.CheckConstraint("outcome IS NULL OR outcome IN ('Success','Failure','Ongoing','Abandoned')", name='ck_poc_tracker_outcome'),
    sa.CheckConstraint('row_version >= 1', name='ck_poc_tracker_row_version_positive'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.opportunity_id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('poc_id')
    )
    op.create_index(op.f('ix_poc_tracker_opportunity_id'), 'poc_tracker', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_poc_tracker_requested_by'), 'poc_tracker', ['requested_by'], unique=False)
    op.create_index(op.f('ix_poc_tracker_status'), 'poc_tracker', ['status'], unique=False)
    op.create_index(op.f('ix_poc_tracker_submitted_by'), 'poc_tracker', ['submitted_by'], unique=False)
    op.create_index(op.f('ix_poc_tracker_row_version'), 'poc_tracker', ['row_version'], unique=False)
    op.create_table('rfx_contexts',
    sa.Column('rfx_context_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('drive_link', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.opportunity_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('rfx_context_id'),
    sa.UniqueConstraint('opportunity_id')
    )
    op.create_table('solution_designs',
    sa.Column('design_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('solution_summary', sa.Text(), nullable=True),
    sa.Column('technical_approach', sa.Text(), nullable=True),
    sa.Column('technical_requirements', sa.Text(), nullable=True),
    sa.Column('architecture_notes', sa.Text(), nullable=True),
    sa.Column('risks', sa.Text(), nullable=True),
    sa.Column('assumptions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.opportunity_id'], ),
    sa.PrimaryKeyConstraint('design_id'),
    sa.UniqueConstraint('opportunity_id')
    )
    op.create_table('stage_history',
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('from_lifecycle_stage', sa.String(length=30), nullable=True),
    sa.Column('to_lifecycle_stage', sa.String(length=30), nullable=True),
    sa.Column('actor_active_role', sa.String(length=50), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.opportunity_id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stage_master.stage_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_stage_history_opportunity_id'), 'stage_history', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_stage_history_stage_id'), 'stage_history', ['stage_id'], unique=False)
    op.create_table('stakeholders',
    sa.Column('stakeholder_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('job_title', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('is_decision_maker', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.opportunity_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stakeholder_id')
    )
    op.create_index(op.f('ix_stakeholders_opportunity_id'), 'stakeholders', ['opportunity_id'], unique=False)
    op.create_index('uq_stakeholder_decision_maker_per_opportunity', 'stakeholders', ['opportunity_id'], unique=True, postgresql_where=sa.text('is_decision_maker = TRUE'), sqlite_where=sa.text('is_decision_maker = 1'))
    op.create_table('activities',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=30), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('follow_up_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['follow_up_id'], ['follow_ups.follow_up_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.opportunity_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_index(op.f('ix_activities_opportunity_id'), 'activities', ['opportunity_id'], unique=False)
    op.create_table('delivery_project_members',
    sa.Column('delivery_project_member_id', sa.Integer(), nullable=False),
    sa.Column('delivery_project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('is_suggested', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['delivery_project_id'], ['delivery_projects.delivery_project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('delivery_project_member_id'),
    sa.UniqueConstraint('delivery_project_id', 'user_id', name='uq_delivery_project_member_user')
    )
    op.create_index(op.f('ix_delivery_project_members_delivery_project_id'), 'delivery_project_members', ['delivery_project_id'], unique=False)
    op.create_index(op.f('ix_delivery_project_members_user_id'), 'delivery_project_members', ['user_id'], unique=False)
    op.create_table('poc_team_members',
    sa.Column('poc_team_member_id', sa.Integer(), nullable=False),
    sa.Column('poc_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['poc_id'], ['poc_tracker.poc_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('poc_team_member_id'),
    sa.UniqueConstraint('poc_id', 'user_id', name='uq_poc_team_member_user')
    )
    op.create_index(op.f('ix_poc_team_members_poc_id'), 'poc_team_members', ['poc_id'], unique=False)
    op.create_index(op.f('ix_poc_team_members_user_id'), 'poc_team_members', ['user_id'], unique=False)
    op.create_table('stakeholder_tag_links',
    sa.Column('stakeholder_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stakeholder_id'], ['stakeholders.stakeholder_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stakeholder_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stakeholder_tag_links')
    op.drop_index(op.f('ix_poc_team_members_user_id'), table_name='poc_team_members')
    op.drop_index(op.f('ix_poc_team_members_poc_id'), table_name='poc_team_members')
    op.drop_table('poc_team_members')
    op.drop_index(op.f('ix_delivery_project_members_user_id'), table_name='delivery_project_members')
    op.drop_index(op.f('ix_delivery_project_members_delivery_project_id'), table_name='delivery_project_members')
    op.drop_table('delivery_project_members')
    op.drop_index(op.f('ix_activities_opportunity_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index('uq_stakeholder_decision_maker_per_opportunity', table_name='stakeholders', postgresql_where=sa.text('is_decision_maker = TRUE'), sqlite_where=sa.text('is_decision_maker = 1'))
    op.drop_index(op.f('ix_stakeholders_opportunity_id'), table_name='stakeholders')
    op.drop_table('stakeholders')
    op.drop_index(op.f('ix_stage_history_stage_id'), table_name='stage_history')
    op.drop_index(op.f('ix_stage_history_opportunity_id'), table_name='stage_history')
    op.drop_table('stage_history')
    op.drop_table('solution_designs')
    op.drop_table('rfx_contexts')
    op.drop_index(op.f('ix_poc_tracker_submitted_by'), table_name='poc_tracker')
    op.drop_index(op.f('ix_poc_tracker_status'), table_name='poc_tracker')
    op.drop_index(op.f('ix_poc_tracker_requested_by'), table_name='poc_tracker')
    op.drop_index(op.f('ix_poc_tracker_row_version'), table_name='poc_tracker')
    op.drop_index(op.f('ix_poc_tracker_opportunity_id'), table_name='poc_tracker')
    op.drop_table('poc_tracker')
    op.drop_index(op.f('ix_opportunity_value_history_opportunity_id'), table_name='opportunity_value_history')
    op.drop_index(op.f('ix_opportunity_value_history_changed_at'), table_name='opportunity_value_history')
    op.drop_index(op.f('ix_opportunity_value_history_actor_id'), table_name='opportunity_value_history')
    op.drop_index(op.f('ix_opportunity_value_history_actor_active_role'), table_name='opportunity_value_history')
    op.drop_table('opportunity_value_history')
    op.drop_index(op.f('ix_opportunity_team_user_id'), table_name='opportunity_team')
    op.drop_index(op.f('ix_opportunity_team_opportunity_id'), table_name='opportunity_team')
    op.drop_table('opportunity_team')
    op.drop_index(op.f('ix_opportunity_oems_opportunity_id'), table_name='opportunity_oems')
    op.drop_index(op.f('ix_opportunity_oems_oem_partner_id'), table_name='opportunity_oems')
    op.drop_table('opportunity_oems')
    op.drop_table('negotiation_contexts')
    op.drop_index(op.f('ix_follow_ups_owner_id'), table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_opportunity_id'), table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_due_date'), table_name='follow_ups')
    op.drop_table('follow_ups')
    op.drop_index(op.f('ix_delivery_projects_opportunity_id'), table_name='delivery_projects')
    op.drop_index(op.f('ix_delivery_projects_manager_id'), table_name='delivery_projects')
    op.drop_index(op.f('ix_delivery_projects_account_id'), table_name='delivery_projects')
    op.drop_table('delivery_projects')
    op.drop_index(op.f('ix_closed_won_requests_status'), table_name='closed_won_requests')
    op.drop_index(op.f('ix_closed_won_requests_opportunity_id'), table_name='closed_won_requests')
    op.drop_table('closed_won_requests')
    op.drop_index(op.f('ix_user_system_permissions_user_id'), table_name='user_system_permissions')
    op.drop_index(op.f('ix_user_system_permissions_permission'), table_name='user_system_permissions')
    op.drop_table('user_system_permissions')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_token_blocklist_user_id'), table_name='token_blocklist')
    op.drop_index(op.f('ix_token_blocklist_jti'), table_name='token_blocklist')
    op.drop_table('token_blocklist')
    op.drop_index(op.f('ix_opportunities_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_stage_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_sales_owner_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_row_version'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_review_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_outcome'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_operational_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_lifecycle_stage'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_created_by'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_account_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_oem_partners_account_id'), table_name='oem_partners')
    op.drop_table('oem_partners')
    op.drop_index(op.f('ix_notifications_recipient_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_entity_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_users_manager_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_stage_master_stage_name'), table_name='stage_master')
    op.drop_table('stage_master')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_accounts_status'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_canonical_name'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_name'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
