"""add index to closed won request requested_at

Revision ID: 889b1b70235a
Revises: b4c5d6e7f8a9
Create Date: 2026-10-01 12:06:45.912670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '889b1b70235a'
down_revision: Union[str, Sequence[str], None] = 'b4c5d6e7f8a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_closed_won_requests_requested_at'), 'closed_won_requests', ['requested_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_closed_won_requests_requested_at'), table_name='closed_won_requests')
    # ### end Alembic commands ###
