"""add opportunity value version

Revision ID: 93e6990990fd
Revises: 2a5516303b0e
Create Date: 2026-09-29 21:56:54.628390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93e6990990fd'
down_revision: Union[str, Sequence[str], None] = '2a5516303b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('value_version', sa.Integer(), server_default='1', nullable=False))
    op.create_index(op.f('ix_opportunities_value_version'), 'opportunities', ['value_version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunities_value_version'), table_name='opportunities')
    op.drop_column('opportunities', 'value_version')
    # ### end Alembic commands ###
